---
- bollera
- cabron
- cabrona
- cabronazo
- capulla
- capullo
- chichi
- chinga
- chingo
- chingon
- chingona
- chingatumadre
- chinga tu madre
- chingada
- chingado
- chocho
- cojon
- cojones
- comepollas
- coño
- culero
- culera
- culo
- follar
- follen
- furcia
- gilipollas
- hijaputa
- hijo puta
- hijo de puta
- hijodeputa
- hijoputa
- hostia
- joder
- jodete
- joputa
- mamada
- mamon
- mamona
- marica
- maricon
- maricona
- mariconazo
- nazi
- ojete
- ostia
- pajillero
- pendon
- pendejo
- pendejos
- pendeja
- pendejas
- pendejada
- pendejadas
- pedo
- pedorra
- pedorro
- pedorron
- picha
- pito
- pelana
- polla
- pollon
- polvo
- potorro
- puta
- puto
- putona
- puton
- tortillera
- weputa
- zorron
